### PR TITLE
Home screen

### PR DESCRIPTION
**Pull request by milesillsley**

### CODE REVIEW

**Review by FiddlersCode — CHANGES_REQUESTED** [review]
If this linter is screaming at us, let's remove before infecting the master branch ;)

**Review by FiddlersCode — DISMISSED** [review]

**Comment by FiddlersCode** [comment]
:shipit:

**Comment by JessicaBarclay** [comment]
I think the nasty linter is part of Atoms linter package 👎

**Review by FiddlersCode — APPROVED** [review]

**Comment by FiddlersCode** [comment]
:shipit:

**Pull request merged**
